WIP FUSETOOLS2-1060 - SASL Plaintext for kafka connection
- set up parameters
- cannot test it with citrus which doesn't allow to have SASL for kafka
Server
- not working with locally Kafka server (but do not know if it is the
server or something else which is badly configured): error on each
request so far:
[2021-04-16 16:51:29,908] WARN [SocketServer brokerId=0] Unexpected
error from /127.0.0.1; closing connection
(org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive
(size = 369295616 larger than 524288)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:105)
	at org.apache.kafka.common.security.authenticator.SaslServerAuthenticator.authenticate(SaslServerAuthenticator.java:249)
	at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:176)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:543)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at kafka.network.Processor.poll(SocketServer.scala:923)
	at kafka.network.Processor.run(SocketServer.scala:826)
	at java.base/java.lang.Thread.run(Thread.java:832)


Signed-off-by: Aurélien Pupier <apupier@redhat.com>